Raw_data <- Read10X(data.dir = Data.path)
seuset_data <- CreateSeuratObject(counts = Raw_data, min.cells = 3, min.features = 200)
seuset_data[["percent.mt"]] <- PercentageFeatureSet(seuset_data, pattern = "mt-")
lb <- quantile(seuset_data[["nFeature_RNA"]]$nFeature_RNA, probs = 0.01)
ub <- quantile(seuset_data[["nFeature_RNA"]]$nFeature_RNA, probs = 0.99)
seuset_data <- seuset_data[, seuset_data[["nFeature_RNA"]] > lb & seuset_data[["nFeature_RNA"]] < ub & seuset_data[["percent.mt"]] < 10]
seuset_data <- NormalizeData(object = seuset_data)
seuset_data <- FindVariableFeatures(object = seuset_data, nfeatures = 5000)
seuset_data <- ScaleData(object = seuset_data, features = rownames(seuset_data))
seuset_data <- RunPCA(object = seuset_data, features = VariableFeatures(object = seuset_data))
seuset_data <- FindNeighbors(object = seuset_data, dims = 1:20)
seuset_data <- FindClusters(object = seuset_data, resolution = 0.5)
seuset_data <- RunTSNE(object = seuset_data, dims = 1:20)
seuset_data <- RunUMAP(object = seuset_data, dims = 1:20)
